# Generated by Django 5.0 on 2023-12-30 04:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50, verbose_name='Month')),
                ('total_meal', models.IntegerField(verbose_name='Total meal')),
                ('meal_rate', models.FloatField(verbose_name='Meal rate')),
                ('total_bazar', models.IntegerField(verbose_name='Total bazar')),
                ('total_mate', models.IntegerField(verbose_name='Total Mate')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('image', models.ImageField(upload_to='user/profiles/', verbose_name='Profile image')),
                ('nid_or_birth', models.ImageField(upload_to='user/nid/', verbose_name='NID or Birth')),
                ('address', models.TextField(max_length=150, verbose_name='Address')),
                ('total_meal', models.IntegerField(default=0, verbose_name='Total meal')),
                ('total_bazar', models.IntegerField(default=0, verbose_name='Total bazar')),
                ('total_tk', models.IntegerField(default=0, verbose_name='Total taka')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date (YYY-MM-DD)')),
                ('bazar', models.IntegerField(verbose_name='Bazar')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazar_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date (YYY-MM-DD)')),
                ('lunch', models.BooleanField(blank=True, null=True, verbose_name='Lunch')),
                ('dinner', models.BooleanField(blank=True, null=True, verbose_name='Dinner')),
                ('comment', models.TextField(max_length=200, verbose_name='Comments')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
