# Generated by Django 5.0 on 2023-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_meal',
            name='dinner',
            field=models.IntegerField(default=0, verbose_name='Dinner'),
        ),
        migrations.AlterField(
            model_name='daily_meal',
            name='lunch',
            field=models.IntegerField(default=0, verbose_name='Lunch'),
        ),
    ]
