# Generated by Django 5.0 on 2023-12-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0002_alter_daily_meal_dinner_alter_daily_meal_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_bazar',
            name='comment',
            field=models.TextField(default=1, max_length=500, verbose_name='Comments'),
            preserve_default=False,
        ),
    ]
