# Generated by Django 5.0 on 2023-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0004_alter_daily_bazar_user_alter_daily_meal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_rate',
            field=models.IntegerField(verbose_name='Meal rate'),
        ),
    ]
